apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-gateway-config
data:
  AWS_IOT_ENDPOINT: {{ .Values.config.awsIotEndpoint | quote }}
  CLIENT_ID: {{ .Values.config.clientId | quote }}
  TOPIC: {{ .Values.config.topic | quote }}
  CERT_PATH: {{ .Values.config.certPath | quote }}
  KEY_PATH: {{ .Values.config.keyPath | quote }}
  CA_PATH: {{ .Values.config.caPath | quote }}
  OPC_UA_URL: {{ .Values.config.opcUaUrl | quote }}
